<?php if (isset($this->albums)): /* /bilder */ ?>
                <div class="row">
                    <div class="col-md-12">
<?php if ($this->user && $this->user->admin): ?>
                        <h1>Bildegalleri<span class="pull-right"><a href="/endre/gallerier" class="btn btn-default">Opprett album</a></span></h1>
<?php else: ?>
                        <h1>Bildegalleri</h1>
<?php endif; ?>
                    </div>
                </div>
<?php if (count($this->albums) > 0): foreach ($this->albums as $category => $albums): ?>
                <div class="row gallery">
                    <div class="col-md-12 galleryYear">
                        <h2><?php echo $category; ?></h2>
                    </div>
<?php foreach ($albums as $album): ?>
                    <div style="height:292px;overflow:hidden;" class="col-xs-6 col-md-3">
                        <a href="/bilder/<?php echo $album->id; ?>" class="thumbnail">
<?php if ($album->cover_image_src): ?>
                            <img src="<?php echo $album->cover_image_src; ?>.thumb.jpg" width="253" height="168" />
<?php else: ?>
                            <div class="noCover text-center">
                                <span style="font-size:220px;" class="glyphicon glyphicon-picture"></span>
                            </div>

<?php endif; ?>
                            <div class="caption">
                                <h3><?php echo $album->title; ?></h3>
                                <small class="text-muted">Publisert <?php echo $album->getPublishedDate(); ?></small>
                            </div>
                        </a>
                    </div>
<?php endforeach; ?>
                </div>
<?php endforeach; else: ?>
                <div class="row">
                    <div class="col-md-12">
                        <div style="margin-top:30px;" class="alert alert-info">
                            Det er ikke lagt ut noen albumer enda
                        </div>
                    </div>
                </div>
<?php endif; ?>
<?php else: /* /bilder/:aid */ ?>
                <div class="row">
                    <div class="col-md-12">
<?php if ($this->user && $this->user->admin): ?>
                        <h1><a href="/bilder">Bildegalleri</a> &raquo; <?php echo $this->album->category; ?> &raquo; <?php echo $this->album->title; ?><span class="pull-right"><a href="/endre/gallerier/gid/<?php echo $this->album->id; ?>" class="btn btn-default">Endre album</a></span></h1>
<?php else: ?>
                        <h1><a href="/bilder">Bildegalleri</a> &raquo; <?php echo $this->album->category; ?> &raquo; <?php echo $this->album->title; ?></h1>
<?php endif; ?>
                    </div>
                </div>
                <div style="margin-top:40px;" class="row gallery">
<?php if (count($this->images) > 0 ):foreach ($this->images as $image): ?>
                    <div class="col-xs-6 col-md-3">
                        <a href="<?php echo $image->src; ?>" class="thumbnail" data-lightbox="album-<?php echo $this->album->id; ?>" data-title="<?php echo $image->title; ?>">
                            <img src="<?php echo $image->src; ?>.thumb.jpg" width="253" height="168" alt="<?php echo $image->title; ?>" />
                        </a>
                        <p style="margin-top:-10px;">
                            <a href="<?php echo $image->src; ?>" target="_blank"><span class="glyphicon glyphicon-zoom-in"></span> Høy oppløsning</a>
<?php if ($this->user && $this->user->admin): ?>
                        <br /><a href="/bilder/<?php echo $this->album->id . '/act/useascover/iid/' . $image->id; ?>"><span class="glyphicon glyphicon-picture"></span> Bruk som album cover</a> &nbsp;&nbsp;&nbsp; <a href="/bilder/<?php echo $this->album->id . '/act/deleteimage/iid/' . $image->id; ?>" onclick="if (!confirm('Er du sikker på at du ønsker å slette bildet over?')) return false;"><span class="glyphicon glyphicon-remove"></span> Slett</a>
<?php endif; ?>
                        </p>
                    </div>
<?php endforeach; else: ?>
                    <div class="col-md-12">
                        <div style="margin-top:30px;" class="alert alert-info">
                            Det er ikke lagt ut noen bilder i dette albummet enda
                        </div>
                    </div>
<?php endif; ?>
<?php if ($this->uploadWidget): ?>
                    <div class="col-sm-12 col-md-12">
                        <hr />
                        <h3>Last opp bilder</h3>
                    </div>
                    <div id="uploader" style="overflow:hidden;" class="col-sm-12 col-md-12">
                        <p>Your browser doesn't have Flash, Silverlight or HTML5 support.</p>
                    </div>
<?php endif; ?>
                </div>
<?php endif; ?>
