                <div class="row">
                    <div class="col-md-12">
                        <h1 class="text-center">Kontoinnstillinger</h1>
                        <div class="col-sm-offset-0 col-sm-12 col-md-offset-3 col-md-6">
<?php if ($this->error): ?>
                            <div class="alert alert-warning">
                                <?php echo $this->error; ?>
                            </div>
<?php endif; ?>
                            <form action="" method="POST" class="form-horizontal">
                                <div class="form-group">
                                    <label for="password">Nåværende passord</label>
                                    <input type="password" name="password" placeholder="Nåværende passord" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label for="newPassword">Nytt passord</label>
                                    <input type="password" name="newPassword" placeholder="Nytt passord" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label for="newPasswordConfirm">Bekreft nytt passord</label>
                                    <input type="password" name="newPasswordConfirm" placeholder="Bekreft nytt passord" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <button type="submit" role="form" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Lagre endringer</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
