<?php $mediaModal = 0; ?>
                <div class="row">
                    <div class="col-md-12">
                        <h1>Marina</h1>
                    </div>
                </div>
<?php if (count($this->marinas) > 0): foreach ($this->marinas as $category => $marinas): ?>
                <div class="fileContainer gallery">
                    <div class="col-md-12 galleryYear">
                        <h2><?php echo $category; ?></h2>
                    </div>
<?php foreach ($marinas as $marina): ?>
                    <div class="col-xs-6 col-md-3 marinaPub">
                        <div class="thumbnail">
                        <a href="<?php echo $marina->src; ?>">
<?php if ($marina->cover_image_src): ?>
                            <img src="<?php echo $marina->cover_image_src; ?>" />
<?php else: ?>
                            <div class="noCover text-center">
                                <span style="font-size:200px;padding:20px 0 0 0;" class="glyphicon glyphicon-file"></span>
                            </div>

<?php endif; ?>
                            <div class="caption">
                                <h3><?php echo $marina->title; ?></h3>
                                <small class="text-muted">Publisert <?php echo $marina->getPublishedDate(); ?></small>
                            </div>
                        </a>
<?php if ($this->user && $this->user->admin): ?>
                        <div class="fileOptions">
                            <a href="/marina/<?php echo $marina->id; ?>"><span class="glyphicon glyphicon-download-alt"></span> Last ned</a>
                            <a href="#" onclick="$(this).parent().siblings('div.imageEdit').toggleClass('hide');return false;"><span class="glyphicon glyphicon-edit"></span> Endre</a>
                            <a href="/marina/<?php echo $marina->id . '/act/deletemarina'; ?>" onclick="if (!confirm('Er du sikker på at du ønsker å slette publikasjonen &laquo;<?php echo $marina->title; ?>&raquo;?')) return false;"><span class="glyphicon glyphicon-remove"></span> Slett</a>
                        </div>
                        <div class="imageEdit well hide" style="position:relative;z-index:9999;">
                            <strong>Endre bilde<span class="pull-right"><button type="button" class="close" onclick="$('div.imageEdit').addClass('hide');"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button></span></strong>
                            <form action="" method="POST" class="form-horizontal">
                                <input type="hidden" name="act" value="editMarina" />
                                <input type="hidden" name="maid" value="<?php echo $marina->id; ?>" />
                                <div style="margin-top:10px;" class="form-group">
                                    <div class="col-md-12">
                                        <div class="input-group">
                                            <input id="image<?php echo $mediaModal++; ?>" type="text" name="image" value="<?php echo $marina->cover_image_src; ?>" class="form-control" />
                                            <div class="input-group-btn">
                                                <button type="button" class="btn btn-default" onclick="$('div.mediaModal-<?php echo ($mediaModal-1); ?> iframe').attr('src', function() {return $(this).data('src');});$('div.mediaModal-<?php echo ($mediaModal-1); ?>').dialog({modal:true, width:875,height:600});"><span class="glyphicon glyphicon-picture"></span> Hent</button>
                                            </div>
                                        </div>
                                        <div style="display:none;" class="mediaModal <?php echo 'mediaModal-' . ($mediaModal-1); ?>">
                                            <iframe data-src="/fileman/index.html?integration=custom&type=image&txtFieldId=<?php echo urlencode('image' . ($mediaModal-1)); ?>" style="width:100%;height:100%" frameborder="0"></iframe>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-default">Lagre endring</button>
                            </form>
                        </div>
<?php else: ?>
    <p style="margin-top:-10px;">
        <a href="/marina/<?php echo $marina->id; ?>"><span class="glyphicon glyphicon-download-alt"></span> Last ned</a>
    </p>
<?php endif; ?>
                    </div>
                    </div>
<?php endforeach; ?>
                </div>
<?php endforeach; else: ?>
                <div class="row">
                    <div class="col-md-12">
                        <div style="margin-top:30px;" class="alert alert-info">
                            Det er ikke lagt ut noen marina enda
                        </div>
                    </div>
                </div>
<?php endif; ?>
<?php if ($this->uploadWidget): ?>
                <div class="col-sm-12 col-md-12">
                    <hr />
                    <h3>Last opp marina for <?php echo (date('M') >= 7 ? date('Y') . '/' . date('Y')+1 : date('Y')-1 . '/' . date('Y')) ?><span class="pull-right"><a href="/endre/marina" class="btn btn-default">Last opp for tidligere år</a></span></h3>
                </div>
                <div id="uploader" style="overflow:hidden;" class="col-sm-12 col-md-12">
                    <p>Your browser doesn't have Flash, Silverlight or HTML5 support.</p>
                </div>
<?php endif; ?>
                <script>
                    function closeMediaBrowser() {
                        $('div.mediaModal').each(function() { if ($(this).hasClass('ui-dialog-content') == true) $(this).dialog('close'); });
                    }
                </script>
