                <div style="margin-top:30px;" class="row">
                    <div class="col-sm-12 col-md-2 submenu">
                        <ul class="nav nav-pills nav-stacked" data-spy="affix" data-offset-top="340" data-offset-bottom="250">
                            <li class="active"><a href="/om">Historie</a></li>
                            <li><a href="/om/statutter">Statutter</a></li>
                            <li><a href="/om/styret">Styret</a></li>
                            <li><a href="/om/undergruppesjefer">Undergruppesjefer</a></li>
                            <li><a href="/om/spr_ktr">ITV/KTR</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-12 col-md-7">
                        <iframe src='http://cdn.knightlab.com/libs/timeline/latest/embed/index.html?source=0Agb95tL3dMRydE1udi1KN0RpZEJqeTNZejhlU0N0OUE&font=Bevan-PotanoSans&maptype=toner&lang=en&height=600' width='100%' height='600' frameborder='0'></iframe>
                    </div>
                    <div class="col-sm-12 col-md-3">
                        <h4>Om mannhullet</h4>
                        <?php echo Model_DbTable_Partials::getHtml('/om:ommannhullet'); ?>
<?php if ($this->user && $this->user->admin): ?>
                        <a href="/endre/partial/pid/2" class="btn btn-default">Endre</a>
<?php endif; ?>
                        <h4>Kontaktinformasjon</h4>
                        <?php echo Model_DbTable_Partials::getHtml('/om:kontakt'); ?>
<?php if ($this->user && $this->user->admin): ?>
                        <a href="/endre/partial/pid/3" class="btn btn-default">Endre</a>
<?php endif; ?>
                    </div>
                </div>
