                <div style="margin-top:30px;" class="row">
                    <div class="col-sm-12 col-md-2 submenu">
                        <ul class="nav nav-pills nav-stacked" data-spy="affix" data-offset-top="340" data-offset-bottom="250">
                            <li class="active"><a href="/om">Om</a></li>
                            <li><a href="/om/historie">Historie</a></li>
                            <li><a href="/om/statutter">Statutter</a></li>
                            <li><a href="/om/styret">Styret</a></li>
                            <li><a href="/om/undergruppesjefer">Undergruppesjefer</a></li>
                            <li><a href="/om/spr_ktr">ITV/KTR</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-12 col-md-10">
                        <h4>Om mannhullet</h4>
                        <?php echo Model_DbTable_Partials::getHtml('/om:ommannhullet'); ?>
<?php if ($this->user && $this->user->admin): ?>
                        <a href="/endre/partial/pid/2" class="btn btn-default">Endre</a>
<?php endif; ?>
                        <h4>Kontaktinformasjon</h4>
                        <?php echo Model_DbTable_Partials::getHtml('/om:kontakt'); ?>
<?php if ($this->user && $this->user->admin): ?>
                        <a href="/endre/partial/pid/3" class="btn btn-default">Endre</a>
<?php endif; ?>
                    </div>
                </div>
