<div style="margin-top:30px;" class="row">
	<div class="col-sm-12 col-md-2 submenu">
		<ul class="nav nav-pills nav-stacked" data-spy="affix" data-offset-top="340" data-offset-bottom="250">
			<li><a href="/om">Om</a></li>
			<li class="active"><a href="/om/historie">Historie</a></li>
			<li><a href="/om/statutter">Statutter</a></li>
			<li><a href="/om/styret">Styret</a></li>
			<li><a href="/om/undergruppesjefer">Undergruppesjefer</a></li>
			<li><a href="/om/spr_ktr">ITV/KTR</a></li>
		</ul>
	</div>
	<div class="col-sm-12 col-md-10">
		<iframe src='https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1BClBDTs_nfPwzQHwJ-PhhS42xB1hTmCWBWRgmOd3ulQ&font=Georgia-Helvetica&lang=en&initial_zoom=2&height=650' width='100%' height='650' webkitallowfullscreen mozallowfullscreen allowfullscreen frameborder='0'></iframe>
	</div>
