<?php if ($this->user ): ?>
  <!DOCTYPE html>
  <html>
  <head>
      <meta charset="utf-8">
      <meta name="blå web nettside mannhullet marin tåkeluren teknikk php javascript">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link href="css\takeluren.css" rel="stylesheet" type="text/css">
      <link href="css\mob.css" rel = "stylesheet" type="text/css" media = "only screen and (max-device-width: 480px)">
      <script src="js\getVerse.js" type="text/javascript"> </script>
      <script src ="js\showVerses.js" type="text/javascript"></script>
      <title>Sjiraffenvers</title>
  </head>
  <!-- Kommentar -->
  <body>
    <div class="row">
        <div class = "col-md-4 col-sm-12">
            <h3>Skriv inn sjiraffenvers:</h3>
            <form method="post" action="saveVerse.php" name="versInput">
              <div class="row">
                <textarea class="inputbox" id="formText" name="formText" rows="4" cols="40"
                  placeholder="Jeg kjøpte meg en himmelseng..." required></textarea>
              </div>

              <div class="row">
                <textarea class="inputbox" id="formAuthor" name="formAuthor" rows="1" cols="40"
                  placeholder="Navn..."></textarea>
              </div>

              <div class="row">
                <textarea class="inputbox" id="formComment" name="formComment" rows="1" cols="40"
                  placeholder="Annen info..."></textarea>
              </div>

              <div = "submitButton row center-block">
              <input type="submit" value="Send inn!" class ="knapp">
             </div>



            </form>
            <div class = "scrollbarWindow">
              <p id="visAlleVers"></p>
            </div>
      </div>



      <div class = "col-md-4 col-sm-12 " >
        <div class="row">
          <button class="center-block" type = "button" onclick="getVerse(<?php $this->verses ?>); " >  <img
            src="tak4.png" style="width:100%;" ></button>
          <p id="plassholder" class="plassholder2 text-center">Trykk på bildet for å få et vers</p>
        </div>

      </div>

      <div class="col-md-4 col-sm-12">
       <p id="visVers" class="mainInfo"></p>
       <p id="visForfatter" class="extraInfo"></p>
       <p id="visKommentar" class="extraInfo"></p>
       <p id="visDato" class="extraInfo"></p>
     </div>
     </div>


     <div class="row">
       <p>
         <?php  foreach ($this->verses as $tekst => $verses):
            echo $tekst;
          endforeach;?>
            <br>
       </p>
     </div>

    </div>









  </div>

  <script src ="js/formValidate.js" type="text/javascript"></script>
  </body>
  </html>

<?php else: ?>
  <h2>Du er ikke innlogget, logg inn for å se sjiraffenversgeneratoren.</h2>
<?php endif; ?>
