<?php if (!isset($this->album)): ?>
                <div style="margin-top:30px;" class="row">
                    <div class="col-sm-12 col-md-12">
                        <h1 style="margin-top:0;">Opprett album</h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-md-12">
                        <form action="" method="post" role="form">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="title">Tittel</label>
                                        <input type="text" name="title" class="form-control" placeholder="" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="category">Albumårstall <small>(når ble bildene tatt)</small></label>
                                        <input type="text" name="category" class="form-control" placeholder="<?php echo $this->currentSchoolYear; ?>" />
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign"></span> Opprett album</button>
                        </form>
                    </div>
                </div>
<?php else: ?>
                <div style="margin-top:30px;" class="row">
                    <div class="col-sm-12 col-md-12">
                        <h1 style="margin-top:0;"><a href="/bilder/<?php echo $this->album->id; ?>"><?php echo $this->album->title; ?></a> &raquo; Endre</h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <form action="" method="POST" role="form">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="title">Tittel</label>
                                        <input type="text" name="title" value="<?php echo $this->album->title; ?>" class="form-control" placeholder="" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="category">Albumårstall <small>(når ble bildene tatt)</small></label>
                                        <input type="text" name="category" value="<?php echo $this->album->category; ?>" class="form-control" placeholder="" />
                                    </div>
                                </div>
                            </div>
                            <button type="submit" name="submit" value="save" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Lagre endringer</button>
                            <a href="/endre/gallerier/gid/<?php echo $this->album->id . '/act/delete'; ?>" onclick="if (!confirm('Er du sikker på at du vil slette albummet &laquo;<?php echo $this->album->title; ?>&raquo; og alle bildene det inneholder?')) return false;" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-remove"></span> Slett <small>(kan ikke angres)</small></a>
                        </form>
                    </div>
<?php if ($this->uploadWidget): ?>
                    <div class="row">
                        <div class="col-sm-12 col-md-12">
                            <hr />
                            <h3>Last opp bilder</h3>
                        </div>
                        <div id="uploader" style="overflow:hidden;" class="col-sm-12 col-md-12">
                            <p>Your browser doesn't have Flash, Silverlight or HTML5 support.</p>
                        </div>
                    </div>
<?php endif; ?>
                </div>
<?php endif; ?>
