                <div class="row gallery">
                    <div class="col-md-12 galleryYear">
                        <h2>Kalender for de første ukene</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;mode=WEEK&amp;height=600&amp;wkst=2&amp;hl=no&amp;bgcolor=%23f2f2f2&amp;src=v54qput2fvcj6iu4st02052nas%40group.calendar.google.com&amp;color=%23182C57&amp;ctz=Europe%2FOslo" style="border-width:0" width="100%" height="600" frameborder="0" scrolling="no"></iframe>
                    </div>
                </div>
