<html>
<body>
<div style="margin: 0; padding: 0; font-family: 'Economica'; background-color: #f2f2f2;">
    <div style="width: 90%; margin: 0 auto; padding: 40px 20px 20px 20px; text-align: center; background-color: #404d75;">
        <img src="http://mannhullet.no/img/logo2.png" />
        <h1 style="color: white; font-size: 40px;">MANNHULLET</h1>
    </div>
    <div style="width: 90%; margin: 0 auto; padding: 30px 20px; background-color: white;">
        <h1 style="margin-top: 0; font-size: 30px;">Du kan nå bli med på Mannhullets nettsider, Marins linjeforening!</h1>
        <p style="font-size: 18px; font-family: 'Sans pro';">Alt er klart for deg på mannhullet.no. Bli med for å få tilgang til <strong>arrangementer, bildegallerier, NTHS-dokumenter, Marina publikasjoner</strong> og mer.</p>
        <p style="font-size: 18px; font-family: 'Sans pro';margin-top:30px;"><a href="http://<?php echo $_SERVER['HTTP_HOST']; ?>/registrer/usr/<?php echo $this->username; ?>">http://<?php echo $_SERVER['HTTP_HOST']; ?></a></p>
    </div>
</div>
</body>
</html>
