<html>
<body>
<div style="margin: 0; padding: 0; font-family: 'Economica'; background-color: #f2f2f2;">
    <div style="width: 90%; margin: 0 auto; padding: 40px 20px 20px 20px; text-align: center; background-color: #404d75;">
        <img src="http://mannhullet.no/img/logo2.png" />
        <h1 style="color: white; font-size: 40px;">MANNHULLET</h1>
    </div>
    <div style="width: 90%; margin: 0 auto; padding: 30px 20px; background-color: white;">
        <h1 style="margin-top: 0; font-size: 30px;">Ditt passord for Mannhullet.no har blitt nullstilt</h1>
        <p style="font-size: 18px; font-family: 'Sans pro';">Passordet ditt har nå blitt nullstilt og et midlertidig passord generert.</p>
        <p style="font-size: 18px; font-family: 'Sans pro';">Logg deg på med det nye passordet, og om ønsket kan du endre det på &laquo;Kontoinnstillinger&raquo; under brukermenyen.</p>
        <p style="font-size: 18px; font-family: 'Sans pro';">Nytt passord: <strong><?php echo $this->password; ?></strong></p>
        <p style="font-size: 18px; font-family: 'Sans pro';margin-top:30px;"><a href="http://<?php echo $_SERVER['HTTP_HOST']; ?>/">Besøk Mannhullet.no</a></p>
    </div>
</div>
</body>
</html>
