                <div style="margin-top:30px;" class="row">
<?php include(__DIR__.'/menu.phtml'); ?>
                    <div class="col-sm-12 col-md-10">
                        <h1 style="margin-top:0;">Media <small>Alle opplastede filer, bilder i nyhetsartikkler osv.</small></h1>
                        <p>Fil-/mappenavn som inneholder æ, ø eller å støttes dessverre ikke.</p>
                        <iframe src="/fileman/index.html" width="100%" height="800" frameborder="0" style="border:1px solid #ddd;box-shadow:#eee 3px 6px 10px 7px;"></iframe>
                    </div>
                </div>
