                    <div class="col-sm-12 col-md-2 submenu">
                        <ul class="nav nav-pills nav-stacked" data-spy="affix" data-offset-top="340" data-offset-bottom="250">
                            <li<?php if ($this->secondarynav == '/admin') echo ' class="active"'; ?>><a href="/admin">Oversikt</a></li>
                            <!--<li<?php if ($this->secondarynav == '/admin/nyheter') echo ' class="active"'; ?>><a href="/admin/nyheter">Nyheter</a></li>-->
                            <li<?php if ($this->secondarynav == '/admin/media') echo ' class="active"'; ?>><a href="/admin/media">Media</a></li>
                            <li<?php if ($this->secondarynav == '/admin/undergrupper') echo ' class="active"'; ?>><a href="/admin/undergrupper">Undergrupper</a></li>
                            <li<?php if ($this->secondarynav == '/admin/medlemmer') echo ' class="active"'; ?>><a href="/admin/medlemmer">Medlemmer</a></li>
                            <li<?php if ($this->secondarynav == '/admin/innstillinger') echo ' class="active"'; ?>><a href="/admin/innstillinger">Innstillinger</a></li>
                        </ul>
                    </div>
