                <div style="margin-top:30px;" class="row">
<?php include(__DIR__.'/menu.phtml'); ?>
                    <div class="col-sm-12 col-md-10">
<?php if (!$this->gid): ?>
                        <div class="row">
                            <div class="col-md-12">
                                <h1 style="margin-top:0;">Undergrupper</h1>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-7">
                                <table style="margin-top:20px;" class="table table-striped table-hover table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Gruppenavn</th>
                                            <th>Farge</th>
                                            <th>Mål</th>
                                        </tr>
                                    </thead>
                                    <tbody>
<?php foreach ($this->groups as $group): ?>
                                        <tr>
                                            <td><a href="/admin/undergrupper/gid/<?php echo $group->id; ?>"><?php echo $group->title; ?></a></td>
                                            <td><div style="width:60px;height:20px;background-color:<?php if ($group->color != null) echo $group->color; ?>;"></div></td>
                                            <td><?php echo ($group->external == null ? 'Intern' : $group->external); ?></td>
                                        </tr>
<?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                            <div class="col-md-5">
                                <h3>Opprett ny undergruppe</h3>
                                <form action="" method="post" role="form">
                                    <div class="form-group">
                                        <label for="title">Navn</label>
                                        <input type="text" name="title" class="form-control" placeholder="" />
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="isExternal" value="external" onclick="$('div.external').toggleClass('hide'); $('div.nonExternal').toggleClass('hide');" /> Dette skal være en ekstern side
                                        </label>
                                    </div>
                                    <div class="external hide">
                                        <div class="form-group">
                                            <label for="external">Lenke som skal åpnes</label>
                                            <input type="text" name="external" class="form-control" placeholder="https://min-gruppe-side.no/" />
                                        </div>
                                    </div>
                                    <div class="nonExternal">
                                        <div class="form-group">
                                            <label for="image">Bannerbilde <small>(653x300, lenke, valgfri)</small></label>
                                            <div class="input-group">
                                                <input id="image" type="text" name="image" class="form-control" placeholder="" />
                                                <div class="input-group-btn">
                                                    <button type="button" class="btn btn-default" onclick="openMediaBrowser();"><span class="glyphicon glyphicon-picture"></span> Hent</button>
                                                </div>
                                            </div>
                                            <div style="display:none;" class="mediaModal">
                                                <iframe src="/fileman/index.html?integration=custom&type=image&txtFieldId=image" style="width:100%;height:100%" frameborder="0">
</iframe>
                                            </div>
                                            <script>
                                                function openMediaBrowser(){
                                                    $('div.mediaModal').dialog({modal:true, width:875,height:600});
                                                }
                                                function closeMediaBrowser(){
                                                    $('div.mediaModal').dialog('close');
                                                }
                                            </script>
                                        </div>
                                        <div class="form-group">
                                            <label for="color">Velg gruppefarge <small>(valgfri)</small></label>
                                            <input type="text" name="color" value="" class="form-control colorPickerTarget" />
                                            <div style="margin-top:5px;">
                                                <button type="button" class="btn btn-default" onclick="var color = Please.make_color();$(this).css('background-color', color);$('input[name=color].colorPickerTarget').val(color);">Generer tilfeldig farge</button>
                                                <button type="button" class="btn btn-default" onclick="$(this).siblings('button').css('background-color', '');$('input[name=color].colorPickerTarget').val('');">Glem farge</button>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="body">Om gruppen</label>
                                            <textarea name="body" rows="5" style="width:100%;" class="form-control"></textarea>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign"></span> Opprett undergruppe</button>
                                </form>
                            </div>
                        </div>
<?php else: ?>
                        <div class="row">
                            <div class="col-md-12">
                                <h1 style="margin-top:0;"><a href="/admin/undergrupper">Undergrupper</a> &raquo; <?php echo $this->group->title; ?></h1>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-7">
                                <form action="" method="post" role="form">
                                    <div class="form-group">
                                        <label for="title">Navn</label>
                                        <input type="text" name="title" value="<?php echo $this->group->title; ?>" class="form-control" placeholder="" />
                                    </div>
<?php if ($this->group->external): ?>
                                    <div class="external">
                                        <div class="form-group">
                                            <label for="external">Lenke som skal åpnes</label>
                                            <input type="text" name="external" value="<?php echo $this->group->external; ?>" class="form-control" placeholder="" />
                                        </div>
                                    </div>
<?php else: ?>
                                    <div class="nonExternal">
                                        <div class="form-group">
                                            <label for="image">Bannerbilde <small>(653x300, lenke, valgfri)</small></label>
                                            <div class="input-group">
                                                <input id="image" type="text" name="image" value="<?php echo $this->group->image; ?>" class="form-control" placeholder="" />
                                                <div class="input-group-btn">
                                                    <button type="button" class="btn btn-default" onclick="openMediaBrowser();"><span class="glyphicon glyphicon-picture"></span> Hent</button>
                                                </div>
                                            </div>
                                            <div style="display:none;" class="mediaModal">
                                                <iframe src="/fileman/index.html?integration=custom&type=image&txtFieldId=image" style="width:100%;height:100%" frameborder="0">
</iframe>
                                            </div>
                                            <script>
                                                function openMediaBrowser(){
                                                    $('div.mediaModal').dialog({modal:true, width:875,height:600});
                                                }
                                                function closeMediaBrowser(){
                                                    $('div.mediaModal').dialog('close');
                                                }
                                            </script>
                                        </div>
                                        <div class="form-group">
                                            <label for="color">Velg gruppefarge <small>(valgfri)</small></label>
                                            <input type="text" name="color" value="<?php if ($this->group->color) echo $this->group->color; ?>" class="form-control colorPickerTarget" />
                                            <div style="margin-top:5px;">
                                                <button type="button"<?php if ($this->group->color) echo ' style="background-color:' . $this->group->color . ';"'; ?> class="btn btn-default" onclick="var color = Please.make_color();$(this).css('background-color', color);$('input[name=color].colorPickerTarget').val(color);">Generer tilfeldig farge</button>
                                                <button type="button" class="btn btn-default" onclick="$(this).siblings('button').css('background-color', '');$('input[name=color].colorPickerTarget').val('');">Glem farge</button>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="body">Om gruppen</label>
                                            <textarea name="body" rows="5" style="width:100%;" class="form-control"><?php echo $this->group->body; ?></textarea>
                                        </div>
                                    </div>
<?php endif; ?>
                                    <button type="submit" name="submit" value="save" class="btn btn-default"><span class="glyphicon glyphicon-ok"></span> Lagre endringer</button>
                                    <button type="submit" name="submit" value="delete" class="btn btn-danger pull-right" onclick="if(!confirm('Er du sikker på at du vil slette undergruppen &laquo;<?php echo $this->group->title; ?>&raquo;')) return false;"><span class="glyphicon glyphicon-remove"></span> Slett undergruppe <small>(all data går tapt)</small></button>
                                </form>
                            </div>
<?php if (!$this->group->external): ?>
                            <div class="col-md-5">
                                <h3>Legg til som gruppeadmin</h3>
                                <form action="" method="post" role="form">
                                    <div class="form-group">
                                        <input type="text" name="name" value="" style="width:100%;" class="form-control typeahead" placeholder="Søk etter bruker" />
                                        <input type="hidden" name="email" value="" style="width:100%;" class="form-control" placeholder="" />
                                    </div>
                                    <button type="submit" name="submit" value="addAdmin" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign"></span> Legg til som gruppeadmin</button>
                                </form>
                                <h3>Gruppeadministratorer</h3>
<?php if (count($this->group->getAdmins()) == 0): ?>
                                <div class="alert alert-info">
                                    Det er ikke lagt til noen gruppeadministratorer enda
                                </div>
<?php else: ?>
                                <table class="table table-hover table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Navn</th>
                                            <th>Handlinger</th>
                                        </tr>
                                    </thead>
                                    <tbody>
<?php foreach ($this->group->getAdmins() as $admin): $user = $admin->getUser(); ?>
                                        <tr>
                                            <td><?php echo $user->name . ' (' . reset(explode('@', $user->email)) . ')'; ?></td>
                                            <td><a href="/admin/undergrupper/gid/<?php echo $this->group->id . '/act/revokeAdmin/uid/' . $user->id; ?>">Fjern</a></td>
                                        </tr>
<?php endforeach; ?>
                                    </tbody>
                                </table>
<?php endif; ?>
                            </div>
<?php endif; ?>
                        </div>
<?php endif; ?>
                    </div>
                </div>
